services:
  test:
    image: sitespeedio/sitespeed.io:35.3.0
    shm_size: 1g
    environment:
      - REPLAY=true
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/sitespeed.io
    command: '--cpu -n 5 --spa -b chrome urls.txt'
