services:
    bumblebee:
        image: sitespeedio/sitespeed.io:latest
        shm_size: 1g
        environment:
            - REPLAY=true
        cap_add:
            - NET_ADMIN
        volumes:
            - .:/sitespeed.io # Mount current directory
        entrypoint: ["/bin/bash", "/sitespeed.io/entrypoint.sh"] # Updated path for entrypoint.sh
        command: ["bumblebee"] # Pass test name dynamically

    nectar:
        image: sitespeedio/sitespeed.io:latest
        shm_size: 1g
        environment:
            - REPLAY=true
        cap_add:
            - NET_ADMIN
        volumes:
            - .:/sitespeed.io
        entrypoint: ["/bin/bash", "/sitespeed.io/entrypoint.sh"]
        command: ["nectar"]

    geoscience-world:
        image: sitespeedio/sitespeed.io:latest
        shm_size: 1g
        environment:
            - REPLAY=true
        cap_add:
            - NET_ADMIN
        volumes:
            - .:/sitespeed.io
        entrypoint: ["/bin/bash", "/sitespeed.io/entrypoint.sh"]
        command: ["geoscience-world"]

    google-scholar:
        image: sitespeedio/sitespeed.io:latest
        shm_size: 1g
        environment:
            - REPLAY=true
        cap_add:
            - NET_ADMIN
        volumes:
            - .:/sitespeed.io
        entrypoint: ["/bin/bash", "/sitespeed.io/entrypoint.sh"]
        command: ["google-scholar"]

    inspire:
        image: sitespeedio/sitespeed.io:latest
        shm_size: 1g
        environment:
            - REPLAY=true
        cap_add:
            - NET_ADMIN
        volumes:
            - .:/sitespeed.io
        entrypoint: ["/bin/bash", "/sitespeed.io/entrypoint.sh"]
        command: ["inspire"]

    pubmed:
        image: sitespeedio/sitespeed.io:latest
        shm_size: 1g
        environment:
            - REPLAY=true
        cap_add:
            - NET_ADMIN
        volumes:
            - .:/sitespeed.io
        entrypoint: ["/bin/bash", "/sitespeed.io/entrypoint.sh"]
        command: ["pubmed"]

    semantic-scholar:
        image: sitespeedio/sitespeed.io:latest
        shm_size: 1g
        environment:
            - REPLAY=true
        cap_add:
            - NET_ADMIN
        volumes:
            - .:/sitespeed.io
        entrypoint: ["/bin/bash", "/sitespeed.io/entrypoint.sh"]
        command: ["semantic-scholar"]
